name: Inject YAML setup to create a Quarto then generate HTML and PDF

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Exoteric: it checks out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Find changed Markdown files
        id: find_files
        run: |
          files = $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.md')
          echo "::set-output name=files::$files"

      - name: Convert Markdown to HTML
        if: steps.find_files.outputs.files != ''
        run: |
          for file in ${{ steps.find_files.outputs.files }}; do
            cat  config.yaml "$file" >> "${file%md}.qmd"
            pandoc --from markdown --to html "${file%qmd}.qmd" -o "${file%.qmd}.html"
            pandoc --from markdown --to pdf "${file%qmd}.qmd" -o "${file%.qmd}.pdf"
          done